P = {
    "programa": [["declara", "rotina", ["begin", "ident", "reserv"], "sentencas", ["end", "ident", "reserv"]]],
    "declara": [[["tipo_var", "variaveis", [";", "simb"], "declara"], [None]]],
    "tipo_var":[[["int", "ident", "reserv"]]],
    "variaveis": [[["id", "mais_var"]]],
    "mais_var": [[[[",", "simb"], "variaveis"], [None]]],
    "rotina": [[["procedimento"], ["funcao"], [None]]],
    "procedimento": [[["proc", "ident", "reserv"], "id", "parametros", [";", "simb"], "declara", ["begin", "ident", "reserv"], "sentencas", ["end", "ident", "reserv"], "rotina"]],
    "funcao": [[["func", "ident", "reserv"], "id", "parametros", [":", "simb"], "tipo_funcao", [";", "simb"], "declara", ["begin", "ident", "reserv"], "sentencas", ["end", "ident", "reserv"], "rotina"]],
    "parametros": [[[["(", "simb"], "lista_parametros", [")", "simb"]], [None]]],
    "lista_parametros": [["lista_id", [":", "simb"], "tipo_var", "cont_lista_par"]],
    "cont_lista_par": [[[[";", "simb"], "lista_parametros"], [None]]],
    "lista_id": [[["id", "cont_lista_id"]]],
    "cont_lista_id":[[[[",", "simb"], "lista_id"], [None]]],
    "tipo_funcao": [[["int", "ident", "reserv"]]],
    "sentencas": [["comando", "mais_sentencas"]],
    "mais_sentencas":[[[";", "simb"], "cont_sentencas"]],
    "cont_sentencas":[[["sentencas"], [None]]],
    "var_read": [["id", "mais_var_read"]],
    "mais_var_read":[[[[",", "simb"], "var_read"], [None]]],
    "var_write": [["id", "mais_var_write"]],
    "mais_var_write": [[[[",", "simb"], "var_write"], [None]]],
    "comando": [[[["read", "ident", "reserv"], "var_read"],
     [["write", "ident", "reserv"], "var_write"],
      [["to", "ident", "reserv"], "id", ["do", "ident", "reserv"],
          "sentencas", ["end", "ident", "reserv"]],
      [["do", "ident", "reserv"], "sentencas", [
          "until", "ident", "reserv"], "condicao"],
      [["while", "ident", "reserv"], "condicao", ["do", "ident",
          "reserv"], "sentencas", ["end", "ident", "reserv"]],
      [["if", "ident", "reserv"], "condicao", ["then", "ident", "reserv"],
          "sentencas", "pfalsa", ["fi", "ident", "reserv"]],
      ["id", [":=", "simb"], "expressao"],
      ["chamada_procedimento"]]],
    "chamada_procedimento": [["id_proc", "argumentos"]],
    "argumentos": [[[["(", "simb"], "lista_arg", [")", "simb"]], [None]]],
    "lista_arg": [["expressao", "cont_lista_arg"]],
    "cont_lista_arg": [[[[",", "simb"], "lista_arg"], [None]]],
    "condicao": [["expressao", "relacao", "expressao"]],
    "pfalsa": [[[["else", "ident", "reserv"], "sentencas"], [None]]],
    "relacao": [[["=", "op", "rel"], [">", "op", "rel"], ["<", "op", "rel"], [">=", "op", "rel"], ["<=", "op", "rel"], ["<>", "op", "rel"]]],
    "expressao": [["termo", "outros_termos"]],
    "op_ad": [[["+", "op", "ad"], ["-", "op", "ad"]]],
    "termo": [[["fator", "mais_fatores"]]],
    "mais_fatores": [[["op_mul", "fator", "mais_fatores"], [None]]],
    "op_mul": [[["*", "op", "mul"], ["/", "op", "mul"]]],
    "fator":[[["id_var"], ["int_num"], [["(", "simb"], "expressao", [")", "simb"]],
     "id_funcao", "argumentos"]],
    "id": [[["", "ident", "id"]]],
    "intnum": [[["", "num"]]],

}

print(P)